/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1proyectogui_gestiondecursos;

import java.security.Principal;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author Usuario
 */
public class Gestion extends javax.swing.JFrame {

    public Gestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoEstudiantes = new javax.swing.JDialog();
        InfoEtudiantes2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        NomEstudiante = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Nidentida = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Guardar2 = new javax.swing.JButton();
        Genero = new javax.swing.JComboBox<>();
        InfoMaestros = new javax.swing.JDialog();
        InfoProfesores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NProfesor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nidentidad2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EdadPr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        Estado = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        AggCursos = new javax.swing.JDialog();
        InfoEtudiantes3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        NomCurso = new javax.swing.JTextField();
        Guardar3 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton7 = new javax.swing.JButton();
        AggMaestros = new javax.swing.JDialog();
        AsignarMaestros = new javax.swing.JPanel();
        Asignar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProfes = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ArbonMa = new javax.swing.JTree();
        Cursos = new javax.swing.JDialog();
        CursosL = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        Bo_AggMaestros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Bo_AggAlumnos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListasCursos = new javax.swing.JList<>();
        AggEstudiantes = new javax.swing.JDialog();
        AsignarMaestros1 = new javax.swing.JPanel();
        Asignar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaEstudiantes = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ArbolEs = new javax.swing.JTree();
        Principal = new javax.swing.JPanel();
        AggEstudiante = new javax.swing.JButton();
        AggProfesor = new javax.swing.JButton();
        AggCurso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        InfoEtudiantes2.setBackground(new java.awt.Color(255, 255, 255));
        InfoEtudiantes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoEtudiantes2MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nombre de el estudiante");

        NomEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        NomEstudiante.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        NomEstudiante.setForeground(new java.awt.Color(0, 0, 0));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Edad");

        Nidentida.setBackground(new java.awt.Color(204, 204, 204));
        Nidentida.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Nidentida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Numero de identidad");

        Edad.setBackground(new java.awt.Color(204, 204, 204));
        Edad.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Edad.setForeground(new java.awt.Color(0, 0, 0));
        Edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdadMouseClicked(evt);
            }
        });
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Sexo");

        Guardar2.setBackground(new java.awt.Color(0, 0, 102));
        Guardar2.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Guardar2.setForeground(new java.awt.Color(255, 255, 255));
        Guardar2.setText("Guardar");
        Guardar2.setBorder(new javax.swing.border.MatteBorder(null));
        Guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar2MouseClicked(evt);
            }
        });
        Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar2ActionPerformed(evt);
            }
        });

        Genero.setBackground(new java.awt.Color(204, 204, 204));
        Genero.setForeground(new java.awt.Color(0, 0, 0));
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoEtudiantes2Layout = new javax.swing.GroupLayout(InfoEtudiantes2);
        InfoEtudiantes2.setLayout(InfoEtudiantes2Layout);
        InfoEtudiantes2Layout.setHorizontalGroup(
            InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEtudiantes2Layout.createSequentialGroup()
                .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoEtudiantes2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(NomEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(Nidentida))
                        .addGap(77, 77, 77)
                        .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InfoEtudiantes2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        InfoEtudiantes2Layout.setVerticalGroup(
            InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEtudiantes2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(InfoEtudiantes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nidentida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout InfoEstudiantesLayout = new javax.swing.GroupLayout(InfoEstudiantes.getContentPane());
        InfoEstudiantes.getContentPane().setLayout(InfoEstudiantesLayout);
        InfoEstudiantesLayout.setHorizontalGroup(
            InfoEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoEtudiantes2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InfoEstudiantesLayout.setVerticalGroup(
            InfoEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoEtudiantes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InfoProfesores.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");

        NProfesor.setBackground(new java.awt.Color(204, 204, 204));
        NProfesor.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        NProfesor.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Edad");

        Nidentidad2.setBackground(new java.awt.Color(204, 204, 204));
        Nidentidad2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Nidentidad2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de identidad");

        EdadPr.setBackground(new java.awt.Color(204, 204, 204));
        EdadPr.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        EdadPr.setForeground(new java.awt.Color(0, 0, 0));
        EdadPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadPrActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sexo");

        Guardar.setBackground(new java.awt.Color(0, 0, 153));
        Guardar.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(204, 204, 204));
        Guardar.setText("Guardar");
        Guardar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Estado Civil");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefono");

        Telefono.setBackground(new java.awt.Color(204, 204, 204));
        Telefono.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });

        genero.setBackground(new java.awt.Color(255, 255, 255));
        genero.setForeground(new java.awt.Color(0, 0, 0));
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        Estado.setBackground(new java.awt.Color(255, 255, 255));
        Estado.setForeground(new java.awt.Color(0, 0, 0));
        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En pareja", "Soltero" }));

        javax.swing.GroupLayout InfoProfesoresLayout = new javax.swing.GroupLayout(InfoProfesores);
        InfoProfesores.setLayout(InfoProfesoresLayout);
        InfoProfesoresLayout.setHorizontalGroup(
            InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoProfesoresLayout.createSequentialGroup()
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoProfesoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(InfoProfesoresLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Nidentidad2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(NProfesor)))
                    .addGroup(InfoProfesoresLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addGroup(InfoProfesoresLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(EdadPr)))
                .addContainerGap())
            .addGroup(InfoProfesoresLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        InfoProfesoresLayout.setVerticalGroup(
            InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoProfesoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EdadPr, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(NProfesor))
                .addGap(26, 26, 26)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nidentidad2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout InfoMaestrosLayout = new javax.swing.GroupLayout(InfoMaestros.getContentPane());
        InfoMaestros.getContentPane().setLayout(InfoMaestrosLayout);
        InfoMaestrosLayout.setHorizontalGroup(
            InfoMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InfoMaestrosLayout.setVerticalGroup(
            InfoMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        InfoEtudiantes3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nombre de el Curso");

        NomCurso.setBackground(new java.awt.Color(204, 204, 204));
        NomCurso.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        NomCurso.setForeground(new java.awt.Color(0, 0, 0));

        Guardar3.setBackground(new java.awt.Color(0, 0, 153));
        Guardar3.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Guardar3.setForeground(new java.awt.Color(255, 255, 255));
        Guardar3.setText("Guardar");
        Guardar3.setBorder(new javax.swing.border.MatteBorder(null));
        Guardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar3MouseClicked(evt);
            }
        });
        Guardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar3ActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Lista de cursos");
        jButton7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        javax.swing.GroupLayout InfoEtudiantes3Layout = new javax.swing.GroupLayout(InfoEtudiantes3);
        InfoEtudiantes3.setLayout(InfoEtudiantes3Layout);
        InfoEtudiantes3Layout.setHorizontalGroup(
            InfoEtudiantes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InfoEtudiantes3Layout.createSequentialGroup()
                .addGroup(InfoEtudiantes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoEtudiantes3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(Guardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoEtudiantes3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(NomCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoEtudiantes3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel19)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        InfoEtudiantes3Layout.setVerticalGroup(
            InfoEtudiantes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEtudiantes3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NomCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Guardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AggCursosLayout = new javax.swing.GroupLayout(AggCursos.getContentPane());
        AggCursos.getContentPane().setLayout(AggCursosLayout);
        AggCursosLayout.setHorizontalGroup(
            AggCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AggCursosLayout.createSequentialGroup()
                .addComponent(InfoEtudiantes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AggCursosLayout.setVerticalGroup(
            AggCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AggCursosLayout.createSequentialGroup()
                .addComponent(InfoEtudiantes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AsignarMaestros.setBackground(new java.awt.Color(255, 255, 255));

        Asignar.setBackground(new java.awt.Color(0, 0, 153));
        Asignar.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Asignar.setForeground(new java.awt.Color(255, 255, 255));
        Asignar.setText("Asignar");
        Asignar.setBorder(new javax.swing.border.MatteBorder(null));
        Asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AsignarMouseClicked(evt);
            }
        });
        Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarActionPerformed(evt);
            }
        });

        ListaProfes.setBackground(new java.awt.Color(204, 204, 204));
        ListaProfes.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ListaProfes);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Asignar maestros");

        ArbonMa.setBackground(new java.awt.Color(204, 204, 204));
        ArbonMa.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cursos");
        ArbonMa.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(ArbonMa);

        javax.swing.GroupLayout AsignarMaestrosLayout = new javax.swing.GroupLayout(AsignarMaestros);
        AsignarMaestros.setLayout(AsignarMaestrosLayout);
        AsignarMaestrosLayout.setHorizontalGroup(
            AsignarMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsignarMaestrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsignarMaestrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        AsignarMaestrosLayout.setVerticalGroup(
            AsignarMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsignarMaestrosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AsignarMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AsignarMaestrosLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AsignarMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AsignarMaestrosLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AsignarMaestrosLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AggMaestrosLayout = new javax.swing.GroupLayout(AggMaestros.getContentPane());
        AggMaestros.getContentPane().setLayout(AggMaestrosLayout);
        AggMaestrosLayout.setHorizontalGroup(
            AggMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarMaestros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AggMaestrosLayout.setVerticalGroup(
            AggMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarMaestros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CursosL.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Lista de cursos");

        jToolBar2.setBackground(new java.awt.Color(0, 0, 204));
        jToolBar2.setForeground(new java.awt.Color(204, 0, 0));
        jToolBar2.setRollover(true);

        Bo_AggMaestros.setBackground(new java.awt.Color(0, 0, 204));
        Bo_AggMaestros.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        Bo_AggMaestros.setForeground(new java.awt.Color(255, 255, 255));
        Bo_AggMaestros.setText("Asignar Maestros");
        Bo_AggMaestros.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Bo_AggMaestros.setFocusable(false);
        Bo_AggMaestros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bo_AggMaestros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bo_AggMaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bo_AggMaestrosMouseClicked(evt);
            }
        });
        jToolBar2.add(Bo_AggMaestros);
        jToolBar2.add(jSeparator1);
        jToolBar2.add(jSeparator2);

        Bo_AggAlumnos.setBackground(new java.awt.Color(0, 0, 204));
        Bo_AggAlumnos.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        Bo_AggAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        Bo_AggAlumnos.setText("Asignar Alumnos");
        Bo_AggAlumnos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Bo_AggAlumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bo_AggAlumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bo_AggAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bo_AggAlumnosMouseClicked(evt);
            }
        });
        Bo_AggAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo_AggAlumnosActionPerformed(evt);
            }
        });
        jToolBar2.add(Bo_AggAlumnos);

        ListasCursos.setBackground(new java.awt.Color(204, 204, 204));
        ListasCursos.setForeground(new java.awt.Color(0, 0, 0));
        ListasCursos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListasCursos);

        javax.swing.GroupLayout CursosLLayout = new javax.swing.GroupLayout(CursosL);
        CursosL.setLayout(CursosLLayout);
        CursosLLayout.setHorizontalGroup(
            CursosLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CursosLLayout.createSequentialGroup()
                .addGroup(CursosLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CursosLLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel29))
                    .addGroup(CursosLLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        CursosLLayout.setVerticalGroup(
            CursosLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CursosLayout = new javax.swing.GroupLayout(Cursos.getContentPane());
        Cursos.getContentPane().setLayout(CursosLayout);
        CursosLayout.setHorizontalGroup(
            CursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CursosL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CursosLayout.setVerticalGroup(
            CursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosLayout.createSequentialGroup()
                .addComponent(CursosL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AsignarMaestros1.setBackground(new java.awt.Color(255, 255, 255));

        Asignar1.setBackground(new java.awt.Color(0, 0, 153));
        Asignar1.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Asignar1.setForeground(new java.awt.Color(255, 255, 255));
        Asignar1.setText("Asignar");
        Asignar1.setBorder(new javax.swing.border.MatteBorder(null));
        Asignar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Asignar1MouseClicked(evt);
            }
        });
        Asignar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asignar1ActionPerformed(evt);
            }
        });

        ListaEstudiantes.setBackground(new java.awt.Color(204, 204, 204));
        ListaEstudiantes.setModel(new DefaultListModel());
        ListaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListaEstudiantes);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Asignar Estudiantes");

        ArbolEs.setBackground(new java.awt.Color(204, 204, 204));
        ArbolEs.setForeground(new java.awt.Color(0, 0, 0));
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cursos");
        ArbolEs.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(ArbolEs);

        javax.swing.GroupLayout AsignarMaestros1Layout = new javax.swing.GroupLayout(AsignarMaestros1);
        AsignarMaestros1.setLayout(AsignarMaestros1Layout);
        AsignarMaestros1Layout.setHorizontalGroup(
            AsignarMaestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsignarMaestros1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Asignar1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsignarMaestros1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(127, 127, 127))
        );
        AsignarMaestros1Layout.setVerticalGroup(
            AsignarMaestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsignarMaestros1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AsignarMaestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AsignarMaestros1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Asignar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AsignarMaestros1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AsignarMaestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AggEstudiantesLayout = new javax.swing.GroupLayout(AggEstudiantes.getContentPane());
        AggEstudiantes.getContentPane().setLayout(AggEstudiantesLayout);
        AggEstudiantesLayout.setHorizontalGroup(
            AggEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarMaestros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AggEstudiantesLayout.setVerticalGroup(
            AggEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarMaestros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setBackground(new java.awt.Color(255, 255, 255));

        AggEstudiante.setBackground(new java.awt.Color(0, 0, 153));
        AggEstudiante.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        AggEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        AggEstudiante.setText("Agregar estudiante");
        AggEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AggEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggEstudianteActionPerformed(evt);
            }
        });

        AggProfesor.setBackground(new java.awt.Color(0, 0, 153));
        AggProfesor.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        AggProfesor.setForeground(new java.awt.Color(255, 255, 255));
        AggProfesor.setText("Agregar Profesor");
        AggProfesor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AggProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AggProfesorMouseClicked(evt);
            }
        });
        AggProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggProfesorActionPerformed(evt);
            }
        });

        AggCurso.setBackground(new java.awt.Color(0, 0, 153));
        AggCurso.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        AggCurso.setForeground(new java.awt.Color(255, 255, 255));
        AggCurso.setText("Agregar Cursos");
        AggCurso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AggCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggCursoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\logo-unitec-color (1).png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AggEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AggProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AggCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AggEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AggProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AggCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AggEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggEstudianteActionPerformed
        InfoEstudiantes.pack();
        InfoEstudiantes.setVisible(true);
        InfoEstudiantes.setLocationRelativeTo(null);
    }//GEN-LAST:event_AggEstudianteActionPerformed

    private void AggProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggProfesorActionPerformed
        InfoMaestros.pack();
        InfoMaestros.setVisible(true);
        InfoMaestros.setLocationRelativeTo(null);
    }//GEN-LAST:event_AggProfesorActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

    }//GEN-LAST:event_GuardarActionPerformed

    private void Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar2ActionPerformed

    }//GEN-LAST:event_Guardar2ActionPerformed

    private void Guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar2MouseClicked

        if (NomEstudiante.getText().isEmpty() || Nidentida.getText().isEmpty() || Edad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(InfoEstudiantes, "Asegurese de llenar todos los campos");
        } else {
            int edad = Integer.parseInt(Edad.getText());
            int identidad = Integer.parseInt(Nidentida.getText());

            if (edad < 1 || edad > 80) {
                JOptionPane.showMessageDialog(InfoEstudiantes, "La edad tiene que ser mayor a 0 y menor o igual a 40");
            } else {
                Alumnos x = new Alumnos();
                x.setNombre(NomEstudiante.getText());
                x.setIdentidad(identidad);
                x.setSexo(Genero.getSelectedItem().toString());
                x.setEdad(edad);

                DefaultListModel model = (DefaultListModel) ListaEstudiantes.getModel();

                model.addElement(x);
                ListaEstudiantes.setModel(model);

                NomEstudiante.setText("");
                Edad.setText("");
                Genero.setSelectedIndex(0);
                Nidentida.setText("");
                JOptionPane.showMessageDialog(InfoEstudiantes, "El Estudiante se agrego exitosamente");
            }
        }
    }//GEN-LAST:event_Guardar2MouseClicked

    private void AggCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggCursoActionPerformed
        AggCursos.pack();
        AggCursos.setVisible(true);
        AggCursos.setLocationRelativeTo(null);
    }//GEN-LAST:event_AggCursoActionPerformed

    private void Guardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar3MouseClicked
        //////uwu////////
        DefaultTreeModel treeModel = (DefaultTreeModel) this.ArbolEs.getModel();
        DefaultMutableTreeNode rootNode = (DefaultMutableTreeNode) treeModel.getRoot();

        String nombre = NomCurso.getText();

        DefaultMutableTreeNode NodoCursos = null;
        for (int i = 0; i < rootNode.getChildCount(); i++) {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) rootNode.getChildAt(i);
            if (node.getUserObject().equals(nombre)) {
                NodoCursos = node;
                break;
            }
        }

        if (NodoCursos == null) {
            NodoCursos = new DefaultMutableTreeNode(nombre);
            rootNode.add(NodoCursos);
            treeModel.reload();
        }
        DefaultMutableTreeNode teamNode = new DefaultMutableTreeNode(new Cursos(nombre));
        NodoCursos.add(teamNode);

        treeModel.reload();

        NomCurso.setText("");

        JOptionPane.showMessageDialog(AggCursos, "Curso creado exitosamente.");
    }//GEN-LAST:event_Guardar3MouseClicked

    private void Guardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Guardar3ActionPerformed

    private void AsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AsignarMouseClicked

        if (ListaProfes.getSelectedIndex() >= 0) {
            DefaultTreeModel treeModel = (DefaultTreeModel) ArbolEs.getModel();
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) ArbolEs.getLastSelectedPathComponent();

            if (selectedNode != null && selectedNode.getUserObject() instanceof Cursos) {
                DefaultListModel jugadorListModel = (DefaultListModel) ListaProfes.getModel();
                String nombre = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getNombre();
                int identidad = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getIdentidad();
                int edad = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getEdad();
                String sexo = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getSexo();
                String estado = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getEstado();
                int telefono = ((Profesores) jugadorListModel.get(ListaProfes.getSelectedIndex())).getTelefono();

                DefaultMutableTreeNode playerNode = new DefaultMutableTreeNode(new Profesores(nombre, identidad, edad, sexo, estado, telefono));
                selectedNode.add(playerNode);

                treeModel.reload();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un curso para agregar profesor");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay profesor seleccionado");
        }
    }//GEN-LAST:event_AsignarMouseClicked

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarActionPerformed

    private void AggProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AggProfesorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AggProfesorMouseClicked

    private void Asignar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Asignar1MouseClicked

        if (ListaEstudiantes.getSelectedIndex() >= 0) {
            DefaultTreeModel treeModel = (DefaultTreeModel) ArbolEs.getModel();
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) ArbolEs.getLastSelectedPathComponent();

            if (selectedNode != null && selectedNode.getUserObject() instanceof Cursos) {
                DefaultListModel jugadorListModel = (DefaultListModel) ListaEstudiantes.getModel();
                String nombre = ((Alumnos) jugadorListModel.get(ListaEstudiantes.getSelectedIndex())).getNombre();
                String sexo = ((Alumnos) jugadorListModel.get(ListaEstudiantes.getSelectedIndex())).getSexo();
                int identidad = ((Alumnos) jugadorListModel.get(ListaEstudiantes.getSelectedIndex())).getIdentidad();
                int edad = ((Alumnos) jugadorListModel.get(ListaEstudiantes.getSelectedIndex())).getEdad();

                DefaultMutableTreeNode playerNode = new DefaultMutableTreeNode(new Alumnos(nombre, sexo, identidad, edad));
                selectedNode.add(playerNode);

                treeModel.reload();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un equipo para agregar jugadores.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay jugador seleccionado.");
        }
    }//GEN-LAST:event_Asignar1MouseClicked

    private void Asignar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asignar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Asignar1ActionPerformed

    private void Bo_AggAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo_AggAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bo_AggAlumnosActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        Cursos.pack();
        Cursos.setVisible(true);
        Cursos.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton7MouseClicked

    private void Bo_AggMaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bo_AggMaestrosMouseClicked
        AggMaestros.pack();
        AggMaestros.setVisible(true);
        AggMaestros.setLocationRelativeTo(null);
    }//GEN-LAST:event_Bo_AggMaestrosMouseClicked

    private void Bo_AggAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bo_AggAlumnosMouseClicked
        AggEstudiantes.pack();
        AggEstudiantes.setVisible(true);
        AggEstudiantes.setLocationRelativeTo(null);
    }//GEN-LAST:event_Bo_AggAlumnosMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked

        if (NProfesor.getText().isEmpty() || Nidentidad2.getText().isEmpty() || EdadPr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(InfoProfesores, "Asegurese de llenar todos los campos");
        } else {
            int edad = Integer.parseInt(EdadPr.getText());
            int identidad = Integer.parseInt(Nidentidad2.getText());

            if (edad < 1 || edad > 80) {
                JOptionPane.showMessageDialog(InfoProfesores, "La edad tiene que ser mayor a 0 y menor o igual a 40");
            } else {
                Profesores x = new Profesores();
                x.setNombre(NProfesor.getText());
                x.setIdentidad(identidad);
                x.setEdad(edad);
                x.setSexo(Genero.getSelectedItem().toString());

                DefaultListModel model = (DefaultListModel) ListaProfes.getModel();

                model.addElement(x);
                ListaProfes.setModel(model);

                NProfesor.setText("");
                Nidentida.setText("");
                EdadPr.setText("");
                Genero.setSelectedIndex(0);
                Estado.setSelectedItem(0);
                Telefono.setText("");

                JOptionPane.showMessageDialog(InfoProfesores, "El Profesor se agrego exitosamente");
            }
        }
    }//GEN-LAST:event_GuardarMouseClicked

    private void InfoEtudiantes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoEtudiantes2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoEtudiantes2MouseClicked

    private void EdadPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadPrActionPerformed

    private void EdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadMouseClicked

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void ListaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEstudiantesMouseClicked

    }//GEN-LAST:event_ListaEstudiantesMouseClicked

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gestion principal = new Gestion();
                principal.pack();
                principal.setLocationRelativeTo(null);
                principal.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggCurso;
    private javax.swing.JDialog AggCursos;
    private javax.swing.JButton AggEstudiante;
    private javax.swing.JDialog AggEstudiantes;
    private javax.swing.JDialog AggMaestros;
    private javax.swing.JButton AggProfesor;
    private javax.swing.JTree ArbolEs;
    private javax.swing.JTree ArbonMa;
    private javax.swing.JButton Asignar;
    private javax.swing.JButton Asignar1;
    private javax.swing.JPanel AsignarMaestros;
    private javax.swing.JPanel AsignarMaestros1;
    private javax.swing.JButton Bo_AggAlumnos;
    private javax.swing.JButton Bo_AggMaestros;
    private javax.swing.JDialog Cursos;
    private javax.swing.JPanel CursosL;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField EdadPr;
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JComboBox<String> Genero;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar2;
    private javax.swing.JButton Guardar3;
    private javax.swing.JDialog InfoEstudiantes;
    private javax.swing.JPanel InfoEtudiantes2;
    private javax.swing.JPanel InfoEtudiantes3;
    private javax.swing.JDialog InfoMaestros;
    private javax.swing.JPanel InfoProfesores;
    private javax.swing.JList<String> ListaEstudiantes;
    private javax.swing.JList<String> ListaProfes;
    private javax.swing.JList<String> ListasCursos;
    private javax.swing.JTextField NProfesor;
    private javax.swing.JTextField Nidentida;
    private javax.swing.JTextField Nidentidad2;
    private javax.swing.JTextField NomCurso;
    private javax.swing.JTextField NomEstudiante;
    private javax.swing.JPanel Principal;
    private javax.swing.JTextField Telefono;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
